name: Vault
main: net.milkbowl.vault.Vault
version: 1.1.6-b000
author: Cereal
softdepend: [ iConomy, BOSEconomy, Essentials, EconXP, eWallet, 3co, MineConomy, MultiCurrency, iChat, mChat, bPermissions, GroupManager, Permissions, PermissionsBukkit, PermissionsEx ]
description: >
             Abstraction Library for Bukkit Plugins
commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
  vault-reload:
    description: Reloads Vault
    usage: |
           /<command> - Reloads Vault
