name: Vault
main: net.milkbowl.vault.Vault
version: 1.2.2-b000
authors: [Cereal, Sleaker]
website: http://dev.bukkit.org/server-mods/vault
load: startup
description: >
             Abstraction Library for Bukkit Plugins
commands:
  vault-info:
    description: Displays information about Vault 
    usage: |
           /<command> - Displays Vault information
  vault-reload:
    description: Reloads Vault
    usage: |
           /<command> - Reloads Vault

permissions:
  vault.admin:
    description: Notifies the player when vault is in need of an update.
    default: op